### ISSUE TITLE
Move all configs to a config folder

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc-starter-app#1]
We have a lot of configuration files in the project root which can be a little intimidating to users. Maybe we can move them to a `./config` folder.

**Comment by daKmoR** [comment]
for most of the config files this can become a hassle... e.g. just running webpack alone is suddenly not good enough... same for eslint, prettier, ... everything that has a CLI

to midigete this we would need to create our own CLI that respects all this... which essentially means becoming a framework...

I thinks our power lies in exactly the opposite... we tell you which tools to use but we don't enforce it... so you can pick and choose what you want... however this also means that every tool has its own config files...  and yes that can be intimidating... however I am not sure if there is a simple solution

**Comment by thepassle** [comment]
> to midigete this we would need to create our own CLI that respects all this... which essentially means becoming a framework...

Agreed, best to avoid this ^
