### ISSUE TITLE
Example doesn't work with IE11

### ISSUE THREAD

**Issue by CarlosTenorio** [open-wc/open-wc-starter-app#11]
I clone the example and I update the _rollup.config.js_ to enable the compatibility with IE11
```
import createCompatibilityConfig from '@open-wc/building-rollup/modern-and-legacy-config';

export default createCompatibilityConfig({ input: './src/index.html' });
```

But is not working on IE11 😔

**Comment by thepassle** [comment]
Hi, this repo has become a bit outdated and runs behind the app generator we have.

I recommend you to use `npm init @open-wc` and scaffold your application from there.

I'll make a to do to update this repo with the output of our generator. If your app scaffolded with the generator still doesnt work in ie11, please create a new issue [here](https://github.com/open-wc/open-wc/issues), preferably with a repo that has a reproduction of the problem.
